# Generated by Django 3.2.25 on 2026-04-02 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender_api', '0004_auto_20260202_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='foods_to_avoid',
            field=models.TextField(blank=True, help_text='Specific foods to avoid'),
        ),
        migrations.AddField(
            model_name='disease',
            name='foods_to_take',
            field=models.TextField(blank=True, help_text='Specific foods to take'),
        ),
        migrations.AddField(
            model_name='disease',
            name='lifestyle_routine',
            field=models.TextField(blank=True, help_text='Lifestyle instructions'),
        ),
        migrations.AddField(
            model_name='disease',
            name='recommended_exercises',
            field=models.TextField(blank=True, help_text='Yoga and exercises'),
        ),
    ]
