# Generated by Django 3.2.25 on 2026-04-02 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender_api', '0005_auto_20260402_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='SymptomDiseaseMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms_combo_key', models.CharField(db_index=True, max_length=500, unique=True)),
                ('disease_name', models.CharField(max_length=200)),
            ],
        ),
    ]
